"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

The page shell, budget metrics, and Gemini chat are wired for you. Your job is
the ONE function marked `BONUS TODO`: `retrieve_for_case(...)`.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

LAYER_ICONS = {
    "short_term": "💬",
    "long_term": "🧠",
    "episodic": "🧭",
    "semantic": "📚",
}

LAYER_LABELS_VI = {
    "short_term": "Short-term",
    "long_term": "Long-term",
    "episodic": "Episodic",
    "semantic": "Semantic",
}

CSS = """
<style>
.block-container { padding-top: 1.6rem; max-width: 1180px; }

h1 { font-weight: 800 !important; letter-spacing: -.01em; }

/* --- layer badges --- */
.lab-badge {
    display:inline-flex; align-items:center; gap:5px;
    padding:3px 12px 3px 8px; border-radius:999px;
    color:#fff; font-size:0.76rem; font-weight:650; letter-spacing:.01em;
    margin-right:6px; margin-bottom:4px;
    box-shadow: 0 1px 2px rgba(0,0,0,.15);
}

/* --- case hero card --- */
.lab-card {
    position:relative; overflow:hidden;
    border:1px solid rgba(128,128,128,.22); border-radius:14px;
    padding:16px 18px 16px 20px; margin-bottom:16px;
    background:rgba(127,127,127,.05);
    box-shadow: 0 1px 3px rgba(0,0,0,.06);
}
.lab-card::before {
    content:""; position:absolute; left:0; top:0; bottom:0; width:5px;
    background: var(--lab-accent, #475569);
}
.lab-card .lab-id { font-size:1.05rem; font-weight:750; margin-left:2px; }
.lab-kv { font-size:0.82rem; opacity:.75; }
.lab-kv b { opacity:1; font-weight:600; }
.lab-query {
    margin:.6rem 0 0; font-size:1.02rem; line-height:1.45; font-weight:500;
}
.lab-desc { font-size:0.8rem; opacity:.65; font-style:italic; }

/* --- section headers --- */
.lab-section {
    display:flex; align-items:center; gap:8px;
    font-size:1.05rem; font-weight:700; margin: 1.1rem 0 .5rem;
}

/* --- budget bar rows --- */
.lab-budget-row { margin-bottom:10px; }
.lab-budget-top {
    display:flex; justify-content:space-between; font-size:0.8rem;
    margin-bottom:3px; opacity:.9;
}
.lab-budget-track {
    height:8px; border-radius:999px; background:rgba(128,128,128,.18); overflow:hidden;
}
.lab-budget-fill { height:100%; border-radius:999px; }

/* --- evidence block --- */
.lab-evidence {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size:0.8rem; line-height:1.55; white-space:pre-wrap; word-break:break-word;
    background:rgba(127,127,127,.07); border:1px solid rgba(128,128,128,.18);
    border-radius:10px; padding:12px 14px; max-height:340px; overflow-y:auto;
}

/* --- misc --- */
.stChatMessage { border-radius:14px; }
.lab-pill-track {
    display:flex; gap:6px; margin: 2px 0 10px; flex-wrap:wrap;
}
.lab-empty { opacity:.55; font-size:0.85rem; font-style:italic; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    icon = LAYER_ICONS.get(case["expected_layer"], "🔹")
    return f"{case['id']} · {icon} {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    icon = LAYER_ICONS.get(layer, "🔹")
    label = LAYER_LABELS_VI.get(layer, layer)
    return f'<span class="lab-badge" style="background:{color}">{icon} {label}</span>'


def budget_bar(layer: str, stats: dict[str, int]) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    icon = LAYER_ICONS.get(layer, "🔹")
    used = stats.get("used_tokens", 0)
    limit = max(1, stats.get("limit_tokens", 1))
    pct = min(100, round(100 * used / limit))
    return (
        '<div class="lab-budget-row">'
        f'<div class="lab-budget-top"><span>{icon} <b>{LAYER_LABELS_VI.get(layer, layer)}</b></span>'
        f'<span>{used} / {limit} tok</span></div>'
        f'<div class="lab-budget-track"><div class="lab-budget-fill" '
        f'style="width:{pct}%;background:{color}"></div></div>'
        "</div>"
    )


def pretty_evidence(text: str) -> str:
    """Insert line breaks before structural markers so raw retrieval text reads
    like a short list instead of one dense wall of characters."""
    if not text:
        return ""
    markers = (
        "EPISODE:", "FACT:", "ENTITY:", "OBSERVATION:", "THREAD_SUMMARY:",
        "<SESSION_SUMMARY>", "<DURABLE_NOTES>", "<RECENT_TURNS>",
        "<USER_SUMMARY>", "<EPISODES>", "<FACTS>",
        "<LONG_TERM>", "<EPISODIC>", "<SEMANTIC>", "<SHORT_TERM>",
    )
    out = text
    for marker in markers:
        out = re.sub(rf"\s*(?<!^)(?={re.escape(marker)})", "\n", out)
    return out.strip()


def _short_term_text(case: dict[str, Any], extra_messages: list[dict[str, str]]) -> str:
    stm = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
    messages = case.get("fixture_messages")
    if not messages:
        dataset = load_dataset()
        user = next((u for u in dataset["users"] if u["user_id"] == case["user_id"]), None)
        session = next(
            (s for s in (user or {}).get("sessions", []) if s["thread_id"] == case.get("thread_id")),
            None,
        )
        messages = (session or {}).get("messages", [])
    for msg in messages or []:
        stm.add(msg["role"], msg["content"])
    for msg in extra_messages or []:
        stm.add(msg["role"], msg["content"])
    return stm.render()


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Run student retrieval for the loaded case, across whichever layers apply.

    Short-term is always included (fixture/session messages + live chat turns)
    so a continued conversation stays coherent. Durable layers are chosen from
    case["expected_layer"] ("mixed" cases use case["retrieve_layers"]).
    """
    query = case.get("query", "")
    user_id = case["user_id"]
    thread_id = case.get("thread_id", "")
    layer = case.get("expected_layer", "mixed")

    default_layers = ["long_term", "semantic"] if layer == "mixed" else [layer]
    wanted = set(case.get("retrieve_layers") or default_layers)
    wanted.add("short_term")

    layers = {"short_term": "", "long_term": "", "episodic": "", "semantic": ""}
    layers["short_term"] = _short_term_text(case, extra_messages)

    if "long_term" in wanted:
        layers["long_term"] = memory.retrieve_long_term(
            user_id=user_id, thread_id=thread_id, query=query
        )
    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)
    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged_context, budget = memory.assemble_context(layers)
    return {"merged_context": merged_context, "layers": layers, "budget": budget}


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Chọn 1 test case, xem agent lấy trí nhớ ở layer nào, rồi chat tiếp với đúng user đó.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        gem_ok = gemini_available()
        st.markdown(("🟢" if zep_ok else "🔴") + " **Zep API key** " + ("OK" if zep_ok else "thiếu"))
        st.markdown(("🟢" if gem_ok else "🟡") + " **Gemini key** " + ("OK" if gem_ok else "thiếu (vẫn chạy được retrieval)"))
        st.caption(f"Chat model: `{settings.gemini_model}`")
        st.divider()
        st.markdown("**Chú giải layer**")
        for lname in ("short_term", "long_term", "episodic", "semantic"):
            st.markdown(layer_badge(lname), unsafe_allow_html=True)
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("📂 Test case", labels)
        case = cases[labels.index(chosen)]

    accent = LAYER_COLORS.get(case.get("expected_layer", ""), "#475569")
    st.markdown(
        f'<div class="lab-card" style="--lab-accent:{accent}">'
        f'{layer_badge(case.get("expected_layer","?"))}'
        f'<span class="lab-id">{case["id"]}</span><br>'
        f'<span class="lab-kv"><b>User:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p class="lab-query">“{case.get("query","")}”</p>'
        + (f'<span class="lab-desc">{case.get("description","")}</span>' if case.get("description") else "")
        + "</div>",
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    if st.button("▶️ Run retrieval trên case này", type="primary"):
        try:
            with st.spinner("Đang truy vấn Zep..."):
                memory = StudentMemory(get_zep_client())
                st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    result = st.session_state.get("last_result")
    if result:
        active = [k for k, v in result["layers"].items() if v.strip()]

        st.markdown('<div class="lab-section">🔎 Layer nào có dữ liệu</div>', unsafe_allow_html=True)
        st.markdown(
            f'<div class="lab-pill-track">{"".join(layer_badge(k) for k in active) or "<span class=lab-empty>(không có gì được lấy về)</span>"}</div>',
            unsafe_allow_html=True,
        )

        if result.get("budget"):
            st.markdown('<div class="lab-section">📊 Token budget mỗi layer (10% / 4% / 3% / 3%)</div>', unsafe_allow_html=True)
            bars = "".join(
                budget_bar(layer_name, result["budget"].get(layer_name, {}))
                for layer_name in ("short_term", "long_term", "episodic", "semantic")
            )
            st.markdown(bars, unsafe_allow_html=True)

        st.markdown('<div class="lab-section">🧩 Merged context (đã cắt theo budget)</div>', unsafe_allow_html=True)
        merged = pretty_evidence(result.get("merged_context") or "")
        st.markdown(f'<div class="lab-evidence">{merged or "(rỗng)"}</div>', unsafe_allow_html=True)

        st.markdown('<div class="lab-section">📜 Chi tiết theo từng layer</div>', unsafe_allow_html=True)
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f'{LAYER_ICONS.get(name,"🔹")} {LAYER_LABELS_VI.get(name, name)} evidence', expanded=False):
                    st.markdown(f'<div class="lab-evidence">{pretty_evidence(text)}</div>', unsafe_allow_html=True)

    st.divider()
    st.markdown('<div class="lab-section">💬 Chat tiếp với đúng user này</div>', unsafe_allow_html=True)
    for msg in st.session_state.get("chat", []):
        avatar = "🧑" if msg["role"] == "user" else "🤖"
        with st.chat_message(msg["role"], avatar=avatar):
            st.write(msg["content"])
            layers_used = msg.get("layers_used")
            if layers_used:
                st.caption("Dùng: " + ", ".join(f"{LAYER_ICONS.get(l,'🔹')} {LAYER_LABELS_VI.get(l,l)}" for l in layers_used))

    prompt = st.chat_input("Nhắn tiếp với vai trò user này…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user", avatar="🧑"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            with st.spinner("Đang truy hồi trí nhớ + soạn câu trả lời..."):
                follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
                st.session_state.last_result = follow
                context = follow.get("merged_context", "")
                if gemini_available():
                    reply = generate_reply(context, st.session_state.chat[:-1], prompt)
                else:
                    reply = ("_(Gemini key missing — showing retrieved context instead)_\n\n"
                             + (context[:1500] or "(no memory retrieved)"))
            layers_used = [k for k, v in follow["layers"].items() if v.strip()]
            st.session_state.chat.append(
                {"role": "assistant", "content": reply, "layers_used": layers_used}
            )
            with st.chat_message("assistant", avatar="🤖"):
                st.write(reply)
                if layers_used:
                    st.caption("Dùng: " + ", ".join(f"{LAYER_ICONS.get(l,'🔹')} {LAYER_LABELS_VI.get(l,l)}" for l in layers_used))
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
